#:schema ./node_modules/wrangler/config-schema.json
name = "studiolinux-admin"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[env.production]
routes = [
  { pattern = "studiolinux.com/api/*", zone_name = "studiolinux.com" }
]
vars = { GITHUB_CLIENT_ID = "YOUR_GITHUB_APP_CLIENT_ID" }

[[env.production.secrets]]
name = "GITHUB_CLIENT_SECRET"

[[env.production.kv_namespaces]]
binding = "TOKENS"
id = "YOUR_KV_NAMESPACE_ID"
preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID"
